[package]
name = "gistory"
version = "0.1.0"
edition = "2024"

[dependencies]
atoi = "2.0.0"
derive_more = { version = "2.0.1", features = ["from"] }
env_logger = "0.11.8"
flate2 = "1.1.2"
futures = "0.3.31"
log = "0.4.27"
tokio = { version = "1.45.1", features = ["full"] }
