[package]
name = "webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
axum-extra = "0.10.1"
env_logger = "0.11.8"
logging = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["fs", "macros", "rt-multi-thread"] }
